### ISSUE TITLE
Can you add 'Start minimized' and 'Minimize to tray with Close button' settings?

### ISSUE THREAD

**Issue by robotnick83** [Zigatronz/Windows-10-WhatsApp-to-Taskbar-Tray#2]
Thank you very much for your software. Please can you add both settings too? That would be great!

**Comment by Zigatronz** [comment]
First and foremost, thanks for using the software and thank you so much for your opinions. It's a really good idea to have start minimized but I'm not sure about minimizing to tray with the close button because I don't know how to mod/change/override the WhatsApp close window button function to my "minimize to tray" function, I probably able to make it possible (but it is not the proper way to do it) with hidden "minimize to tray" button window over the WhatsApp close window button if you don't mind.

Currently, I'm developing v2, and there's a lot to change, organize and fix. Plus, this was made in AHK v1 (tbh, I don't use v1 anymore in terms of code tidiness) so I need to change the whole code to AHK v2 cause I made this repo just for fun and do not expect that ppl actually use it.
